# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [10]:
import numpy as np

arr1=np.random.randint(1 ,21 ,size=(5,5))
print("Original Array:\n",arr1)

arr1[:,2]=1
print("New Array:\n",arr1)

Original Array:
 [[ 1 12 19  3  6]
 [ 6 19 14  7  5]
 [11  2 15 16  4]
 [ 1 16 10  4 19]
 [17 16 17  9  7]]
New Array:
 [[ 1 12  1  3  6]
 [ 6 19  1  7  5]
 [11  2  1 16  4]
 [ 1 16  1  4 19]
 [17 16  1  9  7]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [31]:
arr2=np.random.randint(1 ,17 ,size=(4,4))
print("Original Array:\n",arr2)

np.fill_diagonal(arr2,0)
print("New Array:\n",arr2)

Original Array:
 [[12  8  4 14]
 [14  4 16 16]
 [ 8 14 10  3]
 [ 6  6  3  1]]
New Array:
 [[ 0  8  4 14]
 [14  0 16 16]
 [ 8 14  0  3]
 [ 6  6  3  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.



In [30]:
array=np.random.randint(1,37,size=(6,6))
print(array)
print(array[2:5,1:4])

[[32 29 24 19 26 36]
 [ 6 25 35 27 20 23]
 [32 14 22 17 31 33]
 [ 9  8  5 12 36 30]
 [31 15 27 20 29  7]
 [10 27 27  6  1 24]]
[[14 22 17]
 [ 8  5 12]
 [15 27 20]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [20]:
array=np.random.randint(1,36,size=(5,5))
print(array)

border_element=np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print(border_element)

[[17 33 15  9 34]
 [28 21 11  2  3]
 [ 4 17  9  4 15]
 [19 16 14 26  4]
 [23 29 28 26 27]]
[17 33 15  9 34 23 29 28 26 27 28  4 19  3 15  4]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [22]:
a1=np.random.randint(1,100,size=(3,4))
a2=np.random.randint(1,100,size=(3,4))

print("Addition:\n",a1+a2)
print("Subtraction:\n",a1-a2)
print("Multiplication:\n",a1*a2)
print("Division:\n",a1/a2)

Addition:
 [[164 100  85 180]
 [100 103  48  69]
 [100  95  77  15]]
Subtraction:
 [[  4  72  35  -6]
 [ 60 -53  20 -67]
 [ 60  13 -59   7]]
Multiplication:
 [[6720 1204 1500 8091]
 [1600 1950  476   68]
 [1600 2214  612   44]]
Division:
 [[1.05       6.14285714 2.4        0.93548387]
 [4.         0.32051282 2.42857143 0.01470588]
 [4.         1.31707317 0.13235294 2.75      ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [ ]:
arr1=np.random.randint(1,17,size=(4,4))
print("Array:\n",arr1)

row_sum = np.sum(arr1, axis=1)
column_sum = np.sum(arr1, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)


Array:
 [[11  2  1  6]
 [ 6  3  2 15]
 [ 4  3 12 15]
 [ 4  3 12  1]]
Row-wise sum:
[20 26 34 20]
Column-wise sum:
[25 11 27 37]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [27]:
arr1=np.random.randint(1,16,size=(5,5))
print("Array:\n",arr1)

mean=np.mean(arr1)
median=np.median(arr1)
std=np.std(arr1)
var=np.var(arr1)

print("Mean:",mean)
print("Median:",median)
print("Standard deviation:",std)
print("Variance:",var)

Array:
 [[ 9  3 11 12  6]
 [15  8  8 15 14]
 [12  5  5  3 10]
 [ 2 12  4 10 12]
 [11  8  1 12 10]]
Mean: 8.72
Median: 10.0
Standard deviation: 4.02512111619017
Variance: 16.2016


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [ ]:
arr=np.random.randint(1,10,size=(3,3))
print("Array:\n",arr)

mean=np.mean(arr)
std=np.std(arr)

normalization= (arr-mean)/std
print("Normalization:\n",normalization)

Array:
 [[5 3 2]
 [6 6 2]
 [3 2 8]]
Normalization:
 [[ 0.42761799 -0.53452248 -1.01559272]
 [ 0.90868822  0.90868822 -1.01559272]
 [-0.53452248 -1.01559272  1.87082869]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.



In [39]:
array=np.random.randint(1,10,size=(3,3))
row_arr=np.random.randint(1,10,size=(3,))
print("Array:\n",array)
print("1D Array:",row_arr)

result = array + row_arr
print("Resulting Array:\n",result)

Array:
 [[5 5 5]
 [1 9 5]
 [3 3 7]]
1D Array: [5 7 5]
Resulting Array:
 [[10 12 10]
 [ 6 16 10]
 [ 8 10 12]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [41]:
arr=np.random.randint(1,10,size=(4,4))
sub_arr=np.random.randint(1,10,size=(4,))
print("Array:\n",arr)
print("1D Array:\n",sub_arr)

result=arr-sub_arr.reshape(4,1)
print("Resulting Array:\n",result)

Array:
 [[9 3 3 1]
 [9 8 1 9]
 [6 9 5 4]
 [3 4 8 3]]
1D Array:
 [3 8 3 6]
Resulting Array:
 [[ 6  0  0 -2]
 [ 1  0 -7  1]
 [ 3  6  2  1]
 [-3 -2  2 -3]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.



In [3]:
import numpy as np
arr=np.random.randint(1,10,size=(3,3))
print("Matrix:\n",arr)

determinant=np.linalg.det(arr)
print("Determinant:",determinant)

inverse=np.linalg.inv(arr)
print("Inverse:",inverse)

eigenvalues=np.linalg.eigvals(arr)
print("Eigenvalues:",eigenvalues)


Matrix:
 [[8 7 6]
 [9 4 3]
 [8 5 5]]
Determinant: -29.000000000000004
Inverse: [[-0.17241379  0.17241379  0.10344828]
 [ 0.72413793  0.27586207 -1.03448276]
 [-0.44827586 -0.55172414  1.06896552]]
Eigenvalues: [18.73239364 -2.38225002  0.64985638]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [5]:
m1=np.random.randint(1,10,size=(2,3))
m2=np.random.randint(1,10,size=(3,2))
print("Matrix 1:\n",m1)
print("Matrix 2:\n",m2)
m3=np.dot(m1,m2)
print("Result Matrix:\n",m3)

Matrix 1:
 [[5 4 2]
 [8 2 8]]
Matrix 2:
 [[2 5]
 [9 2]
 [9 8]]
Result Matrix:
 [[ 64  49]
 [106 108]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).



In [8]:
arr=np.random.randint(1,10,size=(3,3))
print("Original:",arr)
reshape_arr=arr.reshape(1,9)
print("Reshape(1,9):",reshape_arr)

reshape_arr_2=arr.reshape(9,1)
print("Reshape(1,9):",reshape_arr_2)


Original: [[9 6 8]
 [3 2 5]
 [6 3 9]]
Reshape(1,9): [[9 6 8 3 2 5 6 3 9]]
Reshape(1,9): [[9]
 [6]
 [8]
 [3]
 [2]
 [5]
 [6]
 [3]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [10]:
arr=np.random.randint(1,11,size=(5,5))
print("Original:\n",arr)
flatten=arr.flatten()
print("Flatten:",flatten)
arr2=flatten.reshape(5,5)
print("Reshape:\n",arr2)

Original:
 [[ 5  6  7  9  7]
 [ 7  6  6 10  3]
 [ 7  9  1  7  2]
 [ 7  9 10  5  5]
 [ 1  3  1  4  3]]
Flatten: [ 5  6  7  9  7  7  6  6 10  3  7  9  1  7  2  7  9 10  5  5  1  3  1  4
  3]
Reshape:
 [[ 5  6  7  9  7]
 [ 7  6  6 10  3]
 [ 7  9  1  7  2]
 [ 7  9 10  5  5]
 [ 1  3  1  4  3]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.



In [12]:
arr=np.random.randint(1,11,size=(5,5))
print("Original array:")
print(arr)

corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 2  8  5  9 10]
 [ 4  8  2  1  3]
 [ 8  8 10  7  6]
 [ 7  5  6  4  8]
 [ 4  3  6  4  6]]
Corner elements:
[ 2 10  4  6]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [15]:
arr=np.random.randint(1,20,size=(5,5))
print("Original array:")
print(arr)
arr[arr>10]=10
print(arr)

Original array:
[[ 2  4  4 18  9]
 [ 6 11 16  3 18]
 [ 4 13 19  7  9]
 [ 7  1 10  6  1]
 [16 16 18 12 12]]
[[ 2  4  4 10  9]
 [ 6 10 10  3 10]
 [ 4 10 10  7  9]
 [ 7  1 10  6  1]
 [10 10 10 10 10]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [21]:
datatype=[('name','U10'), ('age','i4'), ('weight','f4')]
arr=np.array([('Anuj',30,80),('Akash',20,60),('Jaya',26,46)],dtype=datatype)
print(arr)

sort=np.sort(arr,order='age')
print(sort)

[('Anuj', 30, 80.) ('Akash', 20, 60.) ('Jaya', 26, 46.)]
[('Akash', 20, 60.) ('Jaya', 26, 46.) ('Anuj', 30, 80.)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [26]:
datatype=[('x','i4'),('y','i4')]
arr=np.array([(1,1),(2,4),(3,6),(4,8),(5,10)],dtype=datatype)
print(arr)

distance=np.sqrt((arr['x'][:,np.newaxis]-arr['x'])**2+(arr['y'][:,np.newaxis]-arr['y'])**2)
print("distance:",distance)

[(1,  1) (2,  4) (3,  6) (4,  8) (5, 10)]
distance: [[0.         3.16227766 5.38516481 7.61577311 9.8488578 ]
 [3.16227766 0.         2.23606798 4.47213595 6.70820393]
 [5.38516481 2.23606798 0.         2.23606798 4.47213595]
 [7.61577311 4.47213595 2.23606798 0.         2.23606798]
 [9.8488578  6.70820393 4.47213595 2.23606798 0.        ]]



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [29]:
import numpy.ma as ma
arr=np.random.randint(1,21,size=(4,4))
print("Original:\n",arr)
masked_array=ma.masked_greater(arr,10)
print("Masked Array:\n",masked_array)

sum_unmasked_array=masked_array.sum()
print("Sum:",sum_unmasked_array)

Original:
 [[ 8 17 16 15]
 [19  5  6 15]
 [ 2  2  3 15]
 [ 9  5 13 13]]
Masked Array:
 [[8 -- -- --]
 [-- 5 6 --]
 [2 2 3 --]
 [9 5 -- --]]
Sum: 40


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [31]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[17  5 16]
 [19 10 10]
 [ 8 17 10]]
Masked array:
[[-- 5 16]
 [19 -- 10]
 [8 17 --]]
Modified masked array:
[[12  5 16]
 [19 12 10]
 [ 8 17 12]]


4
